[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8000

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = [".", "--output-file", "index.css"]

[watch]
ignore = ["index.css"]
