[package]
name = "a02_is_empty_vec"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.15", features = ["csr", "nightly"] }

[features]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]
